/home/kali/Documentos/API-de-X/env/lib/python3.12/site-packages/pip/_vendor/rich/traceback.#__main__
bfd41bf0069e61928ff091e3b94664de
platform.system
pip._vendor.rich.traceback.error