pip._vendor.urllib3.util.retry.Retry._is_connection_error
b19b17fb35d519312599d19892ddc40e