pip._internal.exceptions._is_kebab_case
dd0d06b7ac419dfd33929e065b07e72f
re.match