pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.format_for_error
971a4894b9b82c1a37332d0441a711cf