
)h11._connection.Connection._process_error^
R/home/kali/Documentos/API-de-X/env/lib/python3.12/site-packages/h11/_connection.pyó ó("2*…
2
ô ô(.

ô ô(.
%1"dictc
a

ô ô(&
%2"__id*G

__unknown_file (+*)
h11._connection.Connection"	
_cstateJ
H

ô ô(-
%3"__id*.

__unknown_file (*

%2"
statesk
i

ô ô(.
%4"dict.__init__*"

__unknown_file (

%1*"

__unknown_file (

%3F
D

ô ô(.

old_states"__id*"

__unknown_file (

%1c
a

õ õ(
%5"__id*G

__unknown_file (+*)
h11._connection.Connection"	
_cstatemk

õ õ((
%6*"

__unknown_file (

%5*$

__unknown_file (

role2process_error˜•

ö ö(2
%7*:

__unknown_file (
h11._connection.Connection**

__unknown_file (


old_states2_respond_to_state_changes*
3*6
3
_connection.py"
ø ø(
implicit return:

ó ó(1
roleB
h11._connection.ConnectionH